#!/usr/bin/env node

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { HttpMethod, OpenApiSpec, OperationCatalogEntry } from "../src/types.js";

const SOURCE_URL =
  process.env.COOLIFY_OPENAPI_SOURCE_URL ??
  "https://raw.githubusercontent.com/coollabsio/coolify/v4.x/openapi.json";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OPENAPI_PATH = path.join(ROOT, "openapi", "coolify-openapi.json");
const DOCS_PATH = path.join(ROOT, "docs", "operations.md");
const GENERATED_SPEC_PATH = path.join(ROOT, "src", "openapi-spec.ts");
const METHODS = ["get", "post", "put", "patch", "delete"] as const;

const response = await fetch(SOURCE_URL);
if (!response.ok) {
  throw new Error(`Failed to fetch Coolify OpenAPI from ${SOURCE_URL}: ${response.status}`);
}

const spec = (await response.json()) as OpenApiSpec;
const operations: OperationCatalogEntry[] = [];

for (const [apiPath, pathItem] of Object.entries(spec.paths ?? {})) {
  for (const method of METHODS) {
    const operation = pathItem[method];
    if (!operation) continue;
    const parameters = operation.parameters ?? [];
    operations.push({
      operationId: operation.operationId ?? `${method}-${apiPath}`,
      method: toHttpMethod(method),
      path: apiPath,
      tag: operation.tags?.[0] ?? "System",
      summary: operation.summary ?? "",
      description: operation.description ?? "",
      pathParameters: parameters
        .filter((parameter) => parameter.in === "path")
        .map((parameter) => parameter.name),
      queryParameters: parameters
        .filter((parameter) => parameter.in === "query")
        .map((parameter) => parameter.name),
      requiredParameters: parameters
        .filter((parameter) => parameter.required)
        .map((parameter) => parameter.name),
      hasRequestBody: Boolean(operation.requestBody),
      requestBodyRequired: isRequiredRequestBody(operation.requestBody),
      responseCodes: Object.keys(operation.responses ?? {}),
    });
  }
}

operations.sort((a, b) => {
  const tag = a.tag.localeCompare(b.tag);
  if (tag !== 0) return tag;
  const pathCompare = a.path.localeCompare(b.path);
  if (pathCompare !== 0) return pathCompare;
  return a.method.localeCompare(b.method);
});

mkdirSync(path.dirname(OPENAPI_PATH), { recursive: true });
mkdirSync(path.dirname(DOCS_PATH), { recursive: true });
mkdirSync(path.dirname(GENERATED_SPEC_PATH), { recursive: true });

writeFileSync(OPENAPI_PATH, JSON.stringify(spec, null, 2) + "\n");
writeFileSync(DOCS_PATH, renderOperationsDoc(spec, operations));
writeFileSync(
  GENERATED_SPEC_PATH,
  `import type { OpenApiSpec } from "./types.js";\n\n` +
    `export const COOLIFY_OPENAPI_SPEC = ${JSON.stringify(spec, null, 2)} as const satisfies OpenApiSpec;\n`,
);

console.log(`Wrote ${OPENAPI_PATH}`);
console.log(`Wrote ${DOCS_PATH}`);
console.log(`Wrote ${GENERATED_SPEC_PATH}`);
console.log(`${operations.length} Coolify operations generated from ${SOURCE_URL}`);

function renderOperationsDoc(spec: OpenApiSpec, operations: OperationCatalogEntry[]): string {
  const byTag = new Map<string, OperationCatalogEntry[]>();
  for (const operation of operations) {
    const tagOperations = byTag.get(operation.tag);
    if (tagOperations) {
      tagOperations.push(operation);
      continue;
    }
    byTag.set(operation.tag, [operation]);
  }

  let markdown = "# Coolify Operation Coverage\n\n";
  markdown += `Source: ${SOURCE_URL}\n\n`;
  markdown += `OpenAPI: ${spec.openapi}\n\n`;
  markdown += `Operations: ${operations.length}\n\n`;
  markdown += "This file is generated by `bun run generate`. Every listed operation is available through the Code Mode `execute` tool via `codemode.request({ operationId })`.\n\n";

  for (const [tag, tagOperations] of [...byTag.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    markdown += `## ${tag}\n\n`;
    markdown += "| Method | Path | Operation ID | Body | Summary |\n";
    markdown += "| --- | --- | --- | --- | --- |\n";
    for (const operation of tagOperations) {
      markdown += `| ${operation.method} | \`${operation.path}\` | \`${operation.operationId}\` | ${operation.hasRequestBody ? "yes" : "no"} | ${escapePipes(operation.summary)} |\n`;
    }
    markdown += "\n";
  }

  return markdown;
}

function toHttpMethod(method: (typeof METHODS)[number]): HttpMethod {
  return method.toUpperCase() as HttpMethod;
}

function isRequiredRequestBody(requestBody: unknown): boolean {
  return (
    typeof requestBody === "object" &&
    requestBody !== null &&
    "required" in requestBody &&
    requestBody.required === true
  );
}

function escapePipes(value: string): string {
  return String(value).replaceAll("|", "\\|");
}
